# Nama workflow yang muncul di GitHub Actions
name: Android CI (Simple WebView Build)

# Event pemicu: Workflow akan berjalan setiap kali ada push ke branch 'main' (atau 'master')
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Job yang akan dijalankan
jobs:
  build:
    # Environment yang digunakan (Ubuntu Linux)
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code: Mendapatkan salinan kode dari repositori
    - uses: actions/checkout@v4

    # 2. Setup Java: Mengatur lingkungan Java yang diperlukan oleh Gradle
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # 3. Grant Execute Permission: Memberikan izin eksekusi ke gradlew (solusi untuk error sebelumnya)
    # Ini harus dijalankan sebelum gradlew digunakan
    - name: Grant Execute Permission to gradlew
      run: chmod +x gradlew

    # 4. Build Debug APK: Menjalankan perintah Gradle untuk membuat APK Debug
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # 5. Upload Artifact: Mengunggah file APK yang sudah jadi
    # Ini agar Anda bisa mengunduh APK langsung dari halaman GitHub Actions
    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        # Path tempat Gradle menyimpan APK
        path: app/build/outputs/apk/debug/app-debug.apk
