# Nama workflow yang muncul di GitHub Actions
name: Android CI (WebView Build)

# Pemicu: Jalankan pada push ke branch utama
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Job yang akan dijalankan
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code: Mendapatkan salinan kode.
    # Menggunakan v3 karena lebih stabil dalam beberapa kasus.
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    # 2. Setup Java: Mengatur lingkungan Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # 3. Grant Execute Permission: Memberikan izin eksekusi ke gradlew.
    # KARENA gradlew ADA DI ROOT, PERINTAH INI HARUS BERJALAN DARI ROOT.
    # Kita tidak perlu mengubah path karena checkout otomatis menempatkan file di root $GITHUB_WORKSPACE.
    - name: Grant Execute Permission to gradlew
      run: chmod +x gradlew

    # 4. Build Debug APK: Menjalankan perintah Gradle.
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # 5. Upload Artifact: Mengunggah file APK yang sudah jadi
    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
